version: '3.8'

services:
  db:
    image: mysql:9.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: g7e4!2wdrc
      MYSQL_DATABASE: scan_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: menduser
      RABBITMQ_DEFAULT_PASS: mendpassword
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - my-network

  app:
    build: .
    container_name: mend-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/scan_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: g7e4!2wdrc
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql-data:
  rabbitmq-data:

